"use client";

import { FormEvent, useMemo, useState } from "react";
import Link from "next/link";
import { beats, formatPrice, getLicense } from "@/lib/beat-catalog";
import { useCart } from "./cart-provider";

type Status = "idle" | "loading" | "error";
export function CheckoutPage() { const { items } = useCart(); const [status, setStatus] = useState<Status>("idle"); const [message, setMessage] = useState(""); const details = useMemo(() => items.flatMap((item) => { const beat = beats.find((candidate) => candidate.slug === item.beatSlug); const license = beat && getLicense(beat, item.licenseId); return beat && license ? [{ beat, license }] : []; }), [items]); const total = details.reduce((sum, item) => sum + item.license.priceCents, 0);
  const submit = async (event: FormEvent<HTMLFormElement>) => { event.preventDefault(); if (!details.length) return; setStatus("loading"); setMessage(""); const form = new FormData(event.currentTarget); try { const result = await fetch("/api/checkout", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ customer: { name: form.get("name"), email: form.get("email"), contact: form.get("contact") }, items }) }); const body = await result.json(); if (!result.ok || !body.initPoint) throw new Error(body.message ?? "Não foi possível iniciar o pagamento."); window.location.assign(body.initPoint); } catch (error) { setStatus("error"); setMessage(error instanceof Error ? error.message : "Não foi possível iniciar o pagamento."); } };
  if (!details.length) return <main className="checkout-page store-page"><section className="beat-empty"><span>◌</span><h2>Seu carrinho ainda está vazio.</h2><Link href="/beats">IR PARA O CATÁLOGO ↗</Link></section></main>;
  return <main className="checkout-page store-page"><section className="store-page__hero"><p className="store-kicker">CHECKOUT SEGURO</p><h1>FINALIZAR <span>COMPRA.</span></h1></section><section className="checkout-layout"><form onSubmit={submit} className="checkout-form"><h2>SEUS DADOS</h2><label>NOME *<input name="name" required autoComplete="name" placeholder="Seu nome completo" /></label><label>E-MAIL *<input name="email" type="email" required autoComplete="email" placeholder="voce@email.com" /></label><label>WHATSAPP OU INSTAGRAM <input name="contact" placeholder="Opcional" /></label><label className="checkout-form__check"><input required type="checkbox" /> <span>Confirmo que meu e-mail está correto e será utilizado para receber os arquivos e informações da compra.</span></label><button disabled={status === "loading"} type="submit">{status === "loading" ? "PROCESSANDO..." : "PAGAR COM MERCADO PAGO ↗"}</button>{status === "error" && <p className="checkout-error" role="alert">{message}</p>}</form><aside className="order-summary"><p>RESUMO DO PEDIDO</p>{details.map(({ beat, license }) => <div key={beat.id}><span>{beat.title} / {license.name}</span><span>{formatPrice(license.priceCents)}</span></div>)}<strong><span>TOTAL</span><span>{formatPrice(total)}</span></strong><small>Os arquivos ficam disponíveis somente após a confirmação segura do pagamento.</small></aside></section></main>; }
